services:
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    env_file:
      - .env

  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - pnpm_store:/pnpm-store
    env_file:
      - .env
    command: sh -c "pnpm install && pnpm dev" # invalidate docker cache when add a package

volumes:
  node_modules:
  pnpm_store:
